### ISSUE TITLE
There are some errors when using jgit diff

### ISSUE THREAD

**Issue by kangofchen** [quarkiverse/quarkus-jgit#104]
error stack：
java.lang.IllegalArgumentException: Enumerated values of type org.eclipse.jgit.diff.DiffAlgorithm$SupportedAlgorithm not available
	at org.eclipse.jgit.lib.Config.allValuesOf(Config.java:427)
	at org.eclipse.jgit.lib.Config.getEnum(Config.java:414)
	at org.eclipse.jgit.diff.DiffFormatter.setReader(DiffFormatter.java:187)
	at org.eclipse.jgit.diff.DiffFormatter.setRepository(DiffFormatter.java:150)
	at org.eclipse.jgit.api.DiffCommand.call(DiffCommand.java:93)

jgit version
api("io.quarkiverse.jgit:quarkus-jgit:3.0.3")

Executing through jar mode can succeed, but compiling to native fails
I don't know if there is a problem with the native configuration file, please help me, thx

**Comment by gastaldi** [comment]
Can you provide a small reproducer?

**Comment by kangofchen** [comment]
Well, I need to take some time to resolve issues related to Git environment dependencies and related account passwords

First of all, thank you for your reply. Wait for me to resolve it

**Comment by kangofchen** [comment]
I tried to peel off the Git environment dependency, but failed

here is my diff step source code

private List<DiffEntry> listDiff(Git git, String oldCommit, String newCommit) throws GitAPIException, IOException {
        return git.diff()
                .setOldTree(prepareTreeParser(git.getRepository(), oldCommit))
                .setNewTree(prepareTreeParser(git.getRepository(), newCommit))
                .call();
    }


private AbstractTreeIterator prepareTreeParser(Repository repository, String objectId) throws IOException {
        // from the commit we can build the tree which allows us to construct the TreeParser
        try (RevWalk walk = new RevWalk(repository)) {
            RevCommit commit = walk.parseCommit(repository.resolve(objectId));
            RevTree tree = walk.parseTree(commit.getTree().getId());

            CanonicalTreeParser treeParser = new CanonicalTreeParser();
            try (ObjectReader reader = repository.newObjectReader()) {
                treeParser.reset(reader, tree.getId());
            }
            walk.dispose();
            return treeParser;
        }
    }


See if there some problems

**Comment by gastaldi** [comment]
I went ahead and released 3.0.5 with this fix. Enjoy!

**Comment by kangofchen** [comment]
> @kangofchen thanks, I have a fix in #105, can you please give it a try and let me know if that works for you?

Great, I passed the test. Thank you for your job
