### ISSUE TITLE
Provide a dev service for git

### ISSUE THREAD

**Issue by iocanel** [quarkiverse/quarkus-jgit#140]
A bit portion if the jgit functionality does require access to a remote server.
Using own accounts on github, gitlab or similar is dangerous in so many different ways:
- accidents can happen
- credentials can leak

It would be so much better / easier for users to have a dev service they can use.

This can also make sense for other extensions using `quarkus-jgit` and their own dev services do require access to a git server (e.g. quarkus-backstage or quarkus-argocd). See:
- https://github.com/quarkiverse/quarkus-backstage/issues/15

### Alterntives (?)
An alternative could be setting up bare repositories. This is something that could work for unit testing etc.
I am not really sure however, if this would be well respected for integration with other extensions, as they may not accept paths etc.

### Implementation ideas
Maybe we could use something like:
- gitea
- gogs
- gitbucket

**Comment by gastaldi** [comment]
We could use something like https://testcontainers.com/modules/git/, which starts a Git server and is a TestContainer module already
