### ISSUE TITLE
Add a DevUI card with a link to the DevService

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-jgit#148]
Now that https://github.com/quarkiverse/quarkus-jgit/issues/140 is implemented, it would be nice if we had a DevUI card with a link to the Gitea DevService and also information about the JGit version used, for example

**Comment by gastaldi** [comment]
@melloware since you're the Dev UI king, are you interested in taking this one?

**Comment by melloware** [comment]
Yep I can take this one.

**Comment by melloware** [comment]
PR Submitted.  I fixed the README as well.
