### ISSUE TITLE
Add org.eclipse.jgit.ssh.apache to the quarkus-jgit plugin

### ISSUE THREAD

**Issue by fage88** [quarkiverse/quarkus-jgit#28]
Since September 2021 github has stopped supporting RSA-1 keys (https://github.blog/2021-09-01-improving-git-protocol-security-github/)

This means users of the quarkus-jgit plugin need to use org.eclipse.jgit.ssh.apache if they want to authenticate with deployment keys as jsch does not support openssl keys.

I would like to see this dependency added to the quarkus-jgit plugin so that users don't need to add it themselves and then try to figure out all of the reflection/native-image issues on their own.

**Comment by gastaldi** [comment]
That would be a great feature to have, would you be interested in providing a pull-request?

**Comment by fage88** [comment]
I can certainly add the dependencies in the pom and all the reflection and proxy classes I have found my application using.

My only concern is that I don't know the org.eclipse.jgit.ssh.apache library particularly well and may very well be leaving other reflection and proxy classes out.  I also don't know how I would unit test this, and would hate to put together a PR with no unit tests in it.

Looking at the current integration-tests it looks like you are setting up a mock git server?  Maybe I could figure out how to make that server treat the repo being cloned as private and grant it access via a deploy key (my usecase in my application) but I am not quite sure how to go about doing that.

**Comment by gastaldi** [comment]
Probably worth investigating if we can start a Gitea server (https://gitea.io) using TestContainers (with the Docker compose module) with SSH enabled

**Comment by gastaldi** [comment]
- https://github.com/quarkiverse/quarkus-jgit/pull/31 upgrades to quarkus-jsch 2.0.0, which depends on https://github.com/mwiede/jsch instead of the original JSch. 

@fage88 can you give it a try if this fixes your issue?

**Comment by fage88** [comment]
Hi @gastaldi,

Thank, you for this.  I updated our project and ti worked great. Good find with this updated fork

-Jeff

**Comment by gastaldi** [comment]
Nice! I'll close this issue for now as the updated fork seems to do the job. Thank you!
